[2024-07-24T05:36:59.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T05:37:00.066+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [queued]>
[2024-07-24T05:37:00.111+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [queued]>
[2024-07-24T05:37:00.114+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T05:37:00.170+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:00:00+00:00
[2024-07-24T05:37:00.217+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=71) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T05:37:00.232+0000] {standard_task_runner.py:64} INFO - Started process 89 to run task
[2024-07-24T05:37:00.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmpoi6uhxlw']
[2024-07-24T05:37:00.259+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask database_connection
[2024-07-24T05:37:00.466+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [running]> on host fc934038a502
[2024-07-24T05:37:01.835+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:00:00+00:00'
[2024-07-24T05:37:01.838+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T05:37:01.841+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T05:37:01.845+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T05:37:01.926+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T05:37:01.941+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T05:37:01.943+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T05:37:01.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T05:37:02.434+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:00:00+00:00, execution_date=20240724T010000, start_date=20240724T053700, end_date=20240724T053702
[2024-07-24T05:37:02.568+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T05:37:02.641+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T05:37:02.646+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-24T09:51:54.824+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:51:55.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [queued]>
[2024-07-24T09:51:55.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [queued]>
[2024-07-24T09:51:55.146+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:51:55.282+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:00:00+00:00
[2024-07-24T09:51:55.334+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:51:55.343+0000] {standard_task_runner.py:64} INFO - Started process 135 to run task
[2024-07-24T09:51:55.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmp8ud1wte6']
[2024-07-24T09:51:55.382+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask database_connection
[2024-07-24T09:51:55.629+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:00:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:51:56.314+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:00:00+00:00'
[2024-07-24T09:51:56.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:51:56.350+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:51:56.351+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:51:56.408+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:51:56.412+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:51:56.420+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:51:56.423+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:51:56.713+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:00:00+00:00, execution_date=20240724T010000, start_date=20240724T095155, end_date=20240724T095156
[2024-07-24T09:51:56.842+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:51:56.988+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:51:56.998+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
