[2024-07-24T05:37:01.541+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T05:37:01.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [queued]>
[2024-07-24T05:37:01.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [queued]>
[2024-07-24T05:37:01.870+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T05:37:01.993+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:05:00+00:00
[2024-07-24T05:37:02.116+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=72) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T05:37:02.123+0000] {standard_task_runner.py:64} INFO - Started process 105 to run task
[2024-07-24T05:37:02.140+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:05:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmppeshrlfn']
[2024-07-24T05:37:02.142+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask database_connection
[2024-07-24T05:37:02.546+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [running]> on host fc934038a502
[2024-07-24T05:37:02.975+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:05:00+00:00'
[2024-07-24T05:37:02.977+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T05:37:02.978+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T05:37:02.983+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T05:37:03.046+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T05:37:03.049+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T05:37:03.050+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T05:37:03.051+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T05:37:03.102+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:05:00+00:00, execution_date=20240724T010500, start_date=20240724T053701, end_date=20240724T053703
[2024-07-24T05:37:03.156+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T05:37:03.211+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T05:37:03.226+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-24T09:51:53.903+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:51:54.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [queued]>
[2024-07-24T09:51:54.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [queued]>
[2024-07-24T09:51:54.130+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:51:54.155+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:05:00+00:00
[2024-07-24T09:51:54.176+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:05:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmp1kak5lib']
[2024-07-24T09:51:54.169+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:51:54.180+0000] {standard_task_runner.py:64} INFO - Started process 122 to run task
[2024-07-24T09:51:54.181+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask database_connection
[2024-07-24T09:51:54.315+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:05:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:51:54.714+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:05:00+00:00'
[2024-07-24T09:51:54.724+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:51:54.725+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:51:54.726+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:51:54.856+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:51:54.878+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:51:54.884+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:51:54.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:51:54.962+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:05:00+00:00, execution_date=20240724T010500, start_date=20240724T095154, end_date=20240724T095154
[2024-07-24T09:51:55.422+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:51:55.561+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:51:55.567+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
