[2024-07-24T05:37:01.936+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T05:37:02.035+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [queued]>
[2024-07-24T05:37:02.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [queued]>
[2024-07-24T05:37:02.070+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T05:37:02.125+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:10:00+00:00
[2024-07-24T05:37:02.142+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T05:37:02.181+0000] {standard_task_runner.py:64} INFO - Started process 106 to run task
[2024-07-24T05:37:02.165+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:10:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmpd7aiuje1']
[2024-07-24T05:37:02.202+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask database_connection
[2024-07-24T05:37:02.560+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [running]> on host fc934038a502
[2024-07-24T05:37:02.911+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:10:00+00:00'
[2024-07-24T05:37:02.913+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T05:37:02.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T05:37:02.915+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T05:37:02.955+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T05:37:02.956+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T05:37:02.957+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T05:37:02.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T05:37:03.031+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:10:00+00:00, execution_date=20240724T011000, start_date=20240724T053702, end_date=20240724T053703
[2024-07-24T05:37:03.109+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T05:37:03.156+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T05:37:03.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-24T09:51:54.870+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T09:51:55.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [queued]>
[2024-07-24T09:51:55.136+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [queued]>
[2024-07-24T09:51:55.136+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-24T09:51:55.256+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): database_connection> on 2024-07-24 01:10:00+00:00
[2024-07-24T09:51:55.301+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T09:51:55.303+0000] {standard_task_runner.py:64} INFO - Started process 134 to run task
[2024-07-24T09:51:55.350+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ETL_Fraud', 'database_connection', 'scheduled__2024-07-24T01:10:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/server_DAG.py', '--cfg-path', '/tmp/tmp85lhw4e0']
[2024-07-24T09:51:55.478+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask database_connection
[2024-07-24T09:51:55.907+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL_Fraud.database_connection scheduled__2024-07-24T01:10:00+00:00 [running]> on host 0542575fe516
[2024-07-24T09:51:56.390+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='test@test.com' AIRFLOW_CTX_DAG_OWNER='fraud_detector' AIRFLOW_CTX_DAG_ID='ETL_Fraud' AIRFLOW_CTX_TASK_ID='database_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T01:10:00+00:00'
[2024-07-24T09:51:56.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T09:51:56.397+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T09:51:56.400+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "database_connection"']
[2024-07-24T09:51:56.567+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T09:51:56.665+0000] {subprocess.py:93} INFO - database_connection
[2024-07-24T09:51:56.666+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-24T09:51:56.675+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T09:51:56.787+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL_Fraud, task_id=database_connection, run_id=scheduled__2024-07-24T01:10:00+00:00, execution_date=20240724T011000, start_date=20240724T095155, end_date=20240724T095156
[2024-07-24T09:51:56.912+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-24T09:51:57.087+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-24T09:51:57.089+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
